#ifndef LYRICSWIKIPLUGIN_GLOBAL_H
#define LYRICSWIKIPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LYRICSWIKIPLUGIN_LIBRARY)
#  define LYRICSWIKIPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LYRICSWIKIPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LYRICSWIKIPLUGIN_GLOBAL_H
